### ISSUE TITLE
Database migration fails: there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/coreupdater#22] opened 2022-04-06 10:17 UTC
I have used Core Updater for adjusting like 200 lines. It seems to work like a charm, but two rows lead to an error:

**1. Different primary key in table ps_page_cache**
`Incorrect table definition; there can be only one auto column and it must be defined as a key`

**2. Column ps_page_type.name should use character set utf8mb4/utf8mb4_unicode_ci instead of utf8/utf8_general_ci**
`Index column size too large. The maximum column size is 767 bytes`

I don't know this objects well and I am using my live store. But I doubt, that I have changed this tables my own.

**Comment by getdatakick** [comment] 2022-04-19 06:38
The first issue is valid, core updater should be able to perform multistep table migration to prevent this kind of errors.

Second issue is not valid, though. This is server misconfiguration. If you tried to install thirty bees from scratch on this mysql server, you would get the same error message.

**Comment by eschiendorfer** [comment] 2022-04-26 19:46
You are right. Only the first issue is real...

**Comment by getdatakick** [comment] 2022-07-15 06:58
Closing as duplicate of #12

**Closed as completed by getdatakick** 2022-07-15 06:58 UTC
Labels: bug
